[package]
name = "dns-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
trust-dns-server = "0.23"
trust-dns-client = "0.23"
trust-dns-proto = "0.23"
trust-dns-resolver = "0.23"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
